package ey.org.model;

// Generated 2014-8-28 10:39:03 by Hibernate Tools 4.0.0

/**
 * Func generated by hbm2java
 */
public class Func implements java.io.Serializable {

	private String id;
	private String funcname;
	private String iseffect;
	private String type;
	private Integer sort;
	private String code;
	private String pid;
	private String funcwholename;
	private String url;

	public Func() {
	}

	public Func(String funcname, String iseffect, String type, Integer sort,
			String code, String pid, String funcwholename, String url) {
		this.funcname = funcname;
		this.iseffect = iseffect;
		this.type = type;
		this.sort = sort;
		this.code = code;
		this.pid = pid;
		this.funcwholename = funcwholename;
		this.url = url;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getFuncname() {
		return this.funcname;
	}

	public void setFuncname(String funcname) {
		this.funcname = funcname;
	}

	public String getIseffect() {
		return this.iseffect;
	}

	public void setIseffect(String iseffect) {
		this.iseffect = iseffect;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getPid() {
		return this.pid;
	}

	public void setPid(String pid) {
		this.pid = pid;
	}

	public String getFuncwholename() {
		return this.funcwholename;
	}

	public void setFuncwholename(String funcwholename) {
		this.funcwholename = funcwholename;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
