package ey.org.model;

// Generated 2014-8-28 10:39:03 by Hibernate Tools 4.0.0

/**
 * FuncRoleRel generated by hbm2java
 */
public class FuncRoleRel implements java.io.Serializable {

	private String id;
	private String orgId;
	private Integer sort;
	private String funcid;
	private String roleid;

	public FuncRoleRel() {
	}

	public FuncRoleRel(String orgId, Integer sort, String funcid, String roleid) {
		this.orgId = orgId;
		this.sort = sort;
		this.funcid = funcid;
		this.roleid = roleid;
	}

	public String getFuncid() {
		return funcid;
	}

	public void setFuncid(String funcid) {
		this.funcid = funcid;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getOrgId() {
		return this.orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}



	public String getRoleid() {
		return this.roleid;
	}

	public void setRoleid(String roleid) {
		this.roleid = roleid;
	}

}
