package ey.org.model;

// Generated 2014-8-28 10:39:03 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private String id;
	private String loginid;
	private String username;
	private String iseffect;
	private String password;
	private Date birthday;
	private String mobile;
	private String fjh;
	private String fphone;
	private String sfzid;
	private String pyjc;
	private String pyqc;
	private String workstate;
	private String orgtype;
	private String duty;
	private String dutydetails;
/*new*/
	private String email;
	private String gender;
	
	
	

	public User() {
	}

	public User(String id) {
		this.id = id;
	}

	public User(String id, String loginid, String username, String iseffect,
			String password, Date birthday, String mobile, String fjh,
			String fphone, String sfzid, String pyjc, String pyqc,
			String workstate, String orgtype, String duty, String dutydetails,
/*new*/			String email, String gender) {
		this.id = id;
		this.loginid = loginid;
		this.username = username;
		this.iseffect = iseffect;
		this.password = password;
		this.birthday = birthday;
		this.mobile = mobile;
		this.fjh = fjh;
		this.fphone = fphone;
		this.sfzid = sfzid;
		this.pyjc = pyjc;
		this.pyqc = pyqc;
		this.workstate = workstate;
		this.orgtype = orgtype;
		this.duty = duty;
		this.dutydetails = dutydetails;
/*new*/ this.email=email;
/*new*/	this.gender=gender;
		
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getLoginid() {
		return this.loginid;
	}

	public void setLoginid(String loginid) {
		this.loginid = loginid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getIseffect() {
		return this.iseffect;
	}

	public void setIseffect(String iseffect) {
		this.iseffect = iseffect;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getFjh() {
		return this.fjh;
	}

	public void setFjh(String fjh) {
		this.fjh = fjh;
	}

	public String getFphone() {
		return this.fphone;
	}

	public void setFphone(String fphone) {
		this.fphone = fphone;
	}

	public String getSfzid() {
		return this.sfzid;
	}

	public void setSfzid(String sfzid) {
		this.sfzid = sfzid;
	}

	public String getPyjc() {
		return this.pyjc;
	}

	public void setPyjc(String pyjc) {
		this.pyjc = pyjc;
	}

	public String getPyqc() {
		return this.pyqc;
	}

	public void setPyqc(String pyqc) {
		this.pyqc = pyqc;
	}

	public String getWorkstate() {
		return this.workstate;
	}

	public void setWorkstate(String workstate) {
		this.workstate = workstate;
	}

	public String getOrgtype() {
		return this.orgtype;
	}

	public void setOrgtype(String orgtype) {
		this.orgtype = orgtype;
	}

	public String getDuty() {
		return this.duty;
	}

	public void setDuty(String duty) {
		this.duty = duty;
	}

	public String getDutydetails() {
		return this.dutydetails;
	}

	public void setDutydetails(String dutydetails) {
		this.dutydetails = dutydetails;
	}
	
	/**
	 * 
	 * @Title: getEmail
	 * @author (wmc)
	 * @date 2014-11-25 上午11:56:38
	 * @return String
	 * @throws
	 * @Description: TODO(xxxxxxxxxxxx)
	 */
	
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}


}
