package ey.org.model;

// Generated 2014-8-28 10:39:03 by Hibernate Tools 4.0.0

/**
 * UserOrgRel generated by hbm2java
 */
public class UserOrgRel implements java.io.Serializable {

	private String id;
	private Integer sort;
	private String ismain;
	private String userid;
	private String orgid;

	public UserOrgRel() {
	}

	public UserOrgRel( Integer sort, String ismain, String userid,
			String orgid) {

		this.sort = sort;
		this.ismain = ismain;
		this.userid = userid;
		this.orgid = orgid;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}



	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	public String getIsmain() {
		return this.ismain;
	}

	public void setIsmain(String ismain) {
		this.ismain = ismain;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

}
