package ey.org.model;

// Generated 2014-8-28 10:39:03 by Hibernate Tools 4.0.0

/**
 * UserRoleRel generated by hbm2java
 */
public class UserRoleRel implements java.io.Serializable {

	private String id;
	private Integer sort;
	private String userid;
	private String roleid;

	public UserRoleRel() {
	}

	public UserRoleRel(Integer sort, String userid, String roleid) {
		this.sort = sort;
		this.userid = userid;
		this.roleid = roleid;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getRoleid() {
		return this.roleid;
	}

	public void setRoleid(String roleid) {
		this.roleid = roleid;
	}

}
