package ey.org.mgmodel;

// Generated 2014-8-28 10:39:03 by Hibernate Tools 4.0.0

/**
 * Role generated by hbm2java
 */
public class RoleOrgMG implements java.io.Serializable {

	private String id;
	private String rolename;
	private String rolesign;
	private String iseffect;
	private String type;
	private Integer sort;
	private String orgid;
	private String rolegroup;
	private String details;
	private String orgwholename;
	
	private String roleWholename;
	
	


	



	public RoleOrgMG() {
	}

	

	public RoleOrgMG(String id, String rolename, String rolesign,
			String iseffect, String type, Integer sort, String orgid,
			String details, String orgwholename,String rolegroup) {
		super();
		this.id = id;
		this.rolename = rolename;
		this.rolesign = rolesign;
		this.iseffect = iseffect;
		this.type = type;
		this.sort = sort;
		this.orgid = orgid;
		this.details = details;
		this.orgwholename = orgwholename;
		this.rolegroup = rolegroup;
	}



	public String getRolegroup() {
		return rolegroup;
	}



	public void setRolegroup(String rolegroup) {
		this.rolegroup = rolegroup;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getRolename() {
		return this.rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	public String getRolesign() {
		return this.rolesign;
	}

	public void setRolesign(String rolesign) {
		this.rolesign = rolesign;
	}

	public String getIseffect() {
		return this.iseffect;
	}

	public void setIseffect(String iseffect) {
		this.iseffect = iseffect;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	public String getDetails() {
		return this.details;
	}

	public void setDetails(String details) {
		this.details = details;
	}
	
	public String getOrgwholename() {
		return orgwholename;
	}



	public void setOrgwholename(String orgwholename) {
		this.orgwholename = orgwholename;
	}

	
	public String getRoleWholename() {
		return orgwholename + "/"+ rolename;
	}
	public void setRoleWholename(String roleWholename) {
		this.roleWholename = roleWholename;
	}

}
