package ey.org.mgmodel;

// Generated 2014-8-28 10:39:03 by Hibernate Tools 4.0.0

/**
 * Role generated by hbm2java
 */
public class UserRoleMG implements java.io.Serializable {
	
	private String userRoleRelid;	
	private String userid;	
	private String roleid;
	private String orgid;
	
	private String rolename;
	private String rolesign;
	private String type;
	private Integer roleSort;	
	private String details;
	private String orgwholename;
	private String roleWholename;
	
	public UserRoleMG() {
	}
	public String getUserid() {
		return userid;
	}






	public void setUserid(String userid) {
		this.userid = userid;
	}






	public String getUserRoleRelid() {
		return userRoleRelid;
	}






	public void setUserRoleRelid(String userRoleRelid) {
		this.userRoleRelid = userRoleRelid;
	}






	public String getRoleid() {
		return roleid;
	}






	public void setRoleid(String roleid) {
		this.roleid = roleid;
	}






	public String getRolename() {
		return rolename;
	}






	public void setRolename(String rolename) {
		this.rolename = rolename;
	}






	public String getRolesign() {
		return rolesign;
	}






	public void setRolesign(String rolesign) {
		this.rolesign = rolesign;
	}






	public String getType() {
		return type;
	}






	public void setType(String type) {
		this.type = type;
	}






	public Integer getRoleSort() {
		return roleSort;
	}






	public void setRoleSort(Integer roleSort) {
		this.roleSort = roleSort;
	}






	public String getOrgid() {
		return orgid;
	}






	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}






	public String getDetails() {
		return details;
	}






	public void setDetails(String details) {
		this.details = details;
	}






	public String getOrgwholename() {
		return orgwholename;
	}






	public void setOrgwholename(String orgwholename) {
		this.orgwholename = orgwholename;
	}






	public String getRoleWholename() {
		return orgwholename + "/"+ rolename;
	}
	public void setRoleWholename(String roleWholename) {
		this.roleWholename = roleWholename;
	}

}
